const GAS_URL='https://script.google.com/macros/s/AKfycbyRP34iPvmw742WWQDWzf1Rwg7Cg9K04HcAkziUJCoygz8VfxbS3Ltx0R_c3fcMuwE/exec';
const categories=['น้ำยาฟอกไต','น้ำยา Disinfectant','ตัวกรองเลือด','สายส่งเลือด','Needle'];
let catalog=[],items=[],page=1,activeCategory='all',selected=new Set(),deferredPrompt;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],thDate=new Intl.DateTimeFormat('th-TH',{dateStyle:'medium'});
const demo=[
 {code:'HEM-0001',name:'Dialysate Concentrate A',category:'น้ำยาฟอกไต',unit:'แกลลอน',received:'2026-07-20',expiry:'2027-05-20',qty:24},
 {code:'HEM-0002',name:'Peracetic Acid Disinfectant',category:'น้ำยา Disinfectant',unit:'แกลลอน',received:'2026-07-18',expiry:'2026-10-15',qty:12},
 {code:'HEM-0003',name:'Dialyzer High Flux',category:'ตัวกรองเลือด',unit:'ชิ้น',received:'2026-06-12',expiry:'2026-07-22',qty:3},
 {code:'HEM-0004',name:'Bloodline Set',category:'สายส่งเลือด',unit:'ชุด',received:'2026-04-22',expiry:'2026-07-10',qty:5},
 {code:'HEM-0005',name:'AV Fistula Needle 16G',category:'Needle',unit:'ชิ้น',received:'2026-07-21',expiry:'2027-07-21',qty:80}
];
const statusInfo={normal:['คงคลังปกติ','#1f9d72','fa-solid fa-circle-check'],today:['หมดอายุวันนี้','#e03131','fa-solid fa-bell'],'6months':['ใกล้หมดอายุ 6 เดือน','#e8a317','fa-solid fa-hourglass-start'],'3months':['ใกล้หมดอายุ 3 เดือน','#ef7a1a','fa-solid fa-hourglass-half'],'1month':['ใกล้หมดอายุ 1 เดือน','#e0481d','fa-solid fa-triangle-exclamation'],expired:['หมดอายุแล้ว','#c92a2a','fa-solid fa-circle-exclamation']};
function today(){return new Date().toISOString().slice(0,10)}
function monthFrom(d,n){const x=new Date(d);x.setMonth(x.getMonth()+n);return x}
function status(i){const n=new Date(today()),e=new Date(i.expiry);if(e<n)return'expired';if(i.expiry===today())return'today';if(e<=monthFrom(n,1))return'1month';if(e<=monthFrom(n,3))return'3months';if(e<=monthFrom(n,6))return'6months';return'normal'}
function normalCategory(value=''){const v=value.toLowerCase();if(v.includes('disinfect')||v.includes('peracetic'))return'น้ำยา Disinfectant';if(v.includes('dialys')||v.includes('น้ำยาฟอก')||v.includes('bicarbonate')||v.includes('acid concentrate'))return'น้ำยาฟอกไต';if(v.includes('dialyzer')||v.includes('filter')||v.includes('ตัวกรอง'))return'ตัวกรองเลือด';if(v.includes('bloodline')||v.includes('สายส่ง'))return'สายส่งเลือด';if(v.includes('needle')||v.includes('เข็ม'))return'Needle';return value}
async function getData(action){const res=await fetch(`${GAS_URL}?action=${action}`,{cache:'no-store'});if(!res.ok)throw Error('API unavailable');return res.json()}
async function loadInventory(showToast=false){try{const d=await getData('inventory');if(d.ok&&Array.isArray(d.items)){items=d.items.map(i=>({...i,category:normalCategory(i.category)}));render();if(showToast)toast('ดึงข้อมูลล่าสุดจาก Google Sheet แล้ว');return}}catch(err){console.info('Inventory API unavailable',err)}if(!items.length){items=demo;render()}if(showToast)toast('ไม่สามารถเชื่อม Google Sheet — แสดงข้อมูลตัวอย่าง')}
async function loadCatalog(){try{const d=await getData('catalog');if(d.ok&&d.items?.length){catalog=d.items.map(x=>({...x,category:normalCategory(x.category)}));populateCatalog();setInInfo();return}}catch(e){console.info('Catalog API unavailable',e)}catalog=demo.map(i=>({name:i.name,category:i.category,unit:i.unit,note:''}));populateCatalog();setInInfo()}
async function gas(action,data){try{await fetch(GAS_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action,...data})});return true}catch(e){return false}}
function renderCards(){const c=Object.fromEntries(Object.keys(statusInfo).map(k=>[k,items.filter(i=>status(i)===k).length]));$('#statusCards').innerHTML=Object.entries(statusInfo).map(([k,[t,color,icon]])=>`<button class="status-card ${$('#statusFilter').value===k?'selected':''}" style="--color:${color}" data-status="${k}"><span class="status-icon"><i class="${icon}"></i></span><b>${c[k]}</b><span>${t}</span></button>`).join('');$$('.status-card').forEach(b=>b.onclick=()=>{$('#statusFilter').value=b.dataset.status;page=1;render()})}
function filtered(){const q=$('#searchInput').value.trim().toLowerCase(),s=$('#statusFilter').value,d=$('#dateFilter').value;return items.filter(i=>(activeCategory==='all'||i.category===activeCategory)&&(!q||i.code.toLowerCase().includes(q)||i.name.toLowerCase().includes(q))&&(s==='all'||status(i)===s)&&(!d||i.expiry<=d))}
function badge(i){const s=status(i),t=statusInfo[s][0],style=s==='normal'?'normal':s==='expired'?'critical':'warning';return`<span class="badge ${style}">${t}</span>`}
function renderTable(){const data=filtered(),per=8,max=Math.max(1,Math.ceil(data.length/per));page=Math.min(page,max);const list=data.slice((page-1)*per,page*per);$('#inventoryBody').innerHTML=list.length?list.map(i=>`<tr><td><input class="row-check" data-code="${i.code}" type="checkbox" ${selected.has(i.code)?'checked':''}></td><td class="code">${i.code}</td><td>${i.name}</td><td>${i.category}</td><td>${thDate.format(new Date(i.received))}</td><td>${thDate.format(new Date(i.expiry))}</td><td class="center qty">${i.qty} ${i.unit}</td><td>${badge(i)}</td><td><button class="table-action print-one" data-code="${i.code}"><i class="fa-solid fa-print"></i> พิมพ์</button><button class="table-action out-one" data-code="${i.code}"><i class="fa-solid fa-arrow-up-right-from-square"></i> ตัดจ่าย</button></td></tr>`).join(''):`<tr><td colspan="9" class="center muted">ไม่พบรายการในหมวดนี้</td></tr>`;$('#itemCount').textContent=`${activeCategory==='all'?'ทุกประเภท':activeCategory} · ${data.length} รายการ`;$('#paginationInfo').textContent=`แสดง ${data.length?(page-1)*per+1:0}–${Math.min(page*per,data.length)} จาก ${data.length}`;$('#pageNo').textContent=`หน้า ${page}/${max}`;$('#prevPage').disabled=page===1;$('#nextPage').disabled=page===max;$('#selectAll').checked=list.length>0&&list.every(i=>selected.has(i.code));$$('.row-check').forEach(e=>e.onchange=()=>{e.checked?selected.add(e.dataset.code):selected.delete(e.dataset.code)});$$('.print-one').forEach(e=>e.onclick=()=>showLabels([e.dataset.code]));$$('.out-one').forEach(e=>e.onclick=()=>openOut(e.dataset.code))}
function renderReports(){const risk=items.filter(i=>status(i)!=='normal'),expired=items.filter(i=>status(i)==='expired');$('#reportCards').innerHTML=[['รายการทั้งหมด',items.length,'#008cab'],['จำนวนคงเหลือ',items.reduce((a,i)=>a+Number(i.qty),0),'#3979d9'],['ต้องเฝ้าระวัง',risk.length,'#e6992c'],['หมดอายุแล้ว',expired.length,'#dd5e69']].map(x=>`<div class="report-card" style="background:${x[2]}"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');$('#reportSummary').innerHTML=`<div><span>หมดอายุแล้ว</span><b>${expired.length} รายการ</b></div><div><span>ใกล้หมดอายุภายใน 3 เดือน</span><b>${items.filter(i=>['today','1month','3months'].includes(status(i))).length} รายการ</b></div><div><span>รวมหน่วยคงเหลือ</span><b>${items.reduce((a,i)=>a+Number(i.qty),0)} หน่วย</b></div>`}
function render(){renderCards();renderTable();renderReports()}
function populateCatalog(){$('#inItem').innerHTML='<option value="">-- เลือกรายการจากชีต Data --</option>'+catalog.map((i,n)=>`<option value="${n}">${i.name}</option>`).join('')}
function setInInfo(){const x=catalog[$('#inItem').value];$('#inCategory').value=x?.category||'';$('#inUnit').value=x?.unit||'';$('#inCode').value=`HEM-${String(items.length+1).padStart(4,'0')}`}
function go(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===id));scrollTo(0,0)}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2800)}
function openOut(code){const i=items.find(x=>x.code===code);if(!i)return toast('ไม่พบ ItemCode');$('#outCode').value=i.code;$('#outName').value=i.name;$('#outBalance').value=`${i.qty} ${i.unit}`;go('stockout')}
function showLabels(codes){const list=items.filter(i=>codes.includes(i.code));if(!list.length)return toast('กรุณาเลือกรายการสำหรับพิมพ์');$('#labels').innerHTML=list.map(i=>`<article class="label-card"><div><h3>${i.name}</h3><p>${i.category}</p><p><b>EXP: ${thDate.format(new Date(i.expiry))}</b></p><p>${i.code}</p></div><div class="qr"></div></article>`).join('');$('#labelDialog').showModal()}
document.addEventListener('DOMContentLoaded',()=>{$('#today').textContent=thDate.format(new Date());$('#inDate').value=$('#outDate').value=today();loadCatalog();loadInventory();$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('.nav-link').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('.inventory-tab').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;page=1;$$('.inventory-tab').forEach(x=>x.classList.toggle('active',x===b));renderTable()});$('#inItem').onchange=setInInfo;['searchInput','statusFilter','dateFilter'].forEach(id=>$('#'+id).oninput=()=>{page=1;render()});$('#refreshBtn').onclick=()=>loadInventory(true);$('#prevPage').onclick=()=>{page--;renderTable()};$('#nextPage').onclick=()=>{page++;renderTable()};$('#selectAll').onchange=e=>{filtered().slice((page-1)*8,page*8).forEach(i=>e.target.checked?selected.add(i.code):selected.delete(i.code));renderTable()};$('#printSelected').onclick=()=>showLabels([...selected]);$('#printHistory').onclick=()=>showLabels(items.map(i=>i.code));$('#stockInForm').onsubmit=async e=>{e.preventDefault();const c=catalog[$('#inItem').value];if(!c)return toast('กรุณาเลือกรายการ');const item={code:$('#inCode').value,name:c.name,category:c.category,unit:c.unit,received:$('#inDate').value,expiry:$('#inExpiry').value,qty:+$('#inQty').value};items.push(item);render();await gas('stockIn',{item,note:$('#inNote').value});showLabels([item.code]);toast('บันทึกรับเข้าแล้ว กำลังปรับปรุง Google Sheet')};$('#outCode').onchange=()=>openOut($('#outCode').value.trim());$('#stockOutForm').onsubmit=async e=>{e.preventDefault();const i=items.find(x=>x.code===$('#outCode').value.trim()),q=+$('#outQty').value;if(!i)return toast('ไม่พบ ItemCode');if(q>i.qty)return toast('จำนวนจ่ายมากกว่าคงเหลือ');i.qty-=q;render();await gas('stockOut',{code:i.code,quantity:q,date:$('#outDate').value,type:$('#outType').value,note:$('#outNote').value});go('dashboard');toast('บันทึกการจ่ายออกแล้ว')};$('#scanBtn').onclick=()=>toast('กรุณาสแกนผ่านกล้องเมื่อเปิดใช้งาน QR scanner');$('#printReport').onclick=()=>print();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{deferredPrompt?.prompt();await deferredPrompt?.userChoice;$('#installBtn').hidden=true}});
